# .github/workflows/main.yml

name: Get Current Date

on:
  push:
    branches:
      - heir

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Upgrade pip
        run: |
          # install pip=>23.2.1 to use "pip cache dir"
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Get pip cache dir
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python get_current_date.py
      
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest

      #- name: Execute Python script
        #run: python get_current_date.py

      - name: Upload Current Date to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          publish_dir: public
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check if pip is installed
        run: pip -V
        shell: sh

      - name: Check if Python is installed
        run: python --version
        shell: sh