# .github/workflows/main.yml

name: Get Current Date

on:
  push:
    branches:
      - heir

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Upgrade pip
        run: |
          # install pip=>23.2.1 to use "pip cache dir"
          python -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Get Current Date
        run: python get_current_date.py
        id: get-current-date
        shell: sh

      - name: Upload Current Date to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          publish_dir: public
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check if pip is installed
        run: pip -V
        shell: sh

      - name: Check if Python is installed
        run: python --version
        shell: sh